steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/$PROJECT_ID/myserver:base || exit 0
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f', 'docker/base.Dockerfile',
    '-t', 'myserver:base',
    '-t', 'gcr.io/$PROJECT_ID/myserver:base',
    '--cache-from', 'gcr.io/$PROJECT_ID/myserver:base',
    '.'
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/myserver:base']
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f', 'docker/Dockerfile',
    '-t', 'gcr.io/$PROJECT_ID/myserver:latest',
    '.'
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f', 'docker/coverage.Dockerfile',
    '-t', 'gcr.io/$PROJECT_ID/myserver:coverage',
    '.'
  ]

images:
- 'gcr.io/$PROJECT_ID/myserver:base'
- 'gcr.io/$PROJECT_ID/myserver:latest'
- 'gcr.io/$PROJECT_ID/myserver:coverage'
